// let a : number = (4**2+4-6/2);
// console.log(a);
var a = 10;
var b = 6;
console.log("a + b", a + b);
console.log("a - b", a - b);
console.log("a * b", a * b);
console.log("a / b", a / b);
console.log("a % b", a & b);
console.log("a ** b", Math.pow(a, b));
